"""add telegram_message_id field

Revision ID: 04561ada7418
Revises: 93532b7056b8
Create Date: 2026-02-06 06:31:48.799757

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04561ada7418"
down_revision: Union[str, Sequence[str], None] = "93532b7056b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings", sa.Column("telegram_message_id", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "telegram_message_id")
    # ### end Alembic commands ###
