"""add default value for changed_at filed

Revision ID: 0a66d343d9f5
Revises: b30e66a75ec2
Create Date: 2026-02-02 04:25:25.026898

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a66d343d9f5"
down_revision: Union[str, Sequence[str], None] = "b30e66a75ec2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE bookings SET changed_at = NOW() WHERE changed_at IS NULL")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
