"""change excursions details table

Revision ID: 0f587df53993
Revises: e1fd5f174f86
Create Date: 2025-12-06 16:41:11.294253

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0f587df53993"
down_revision: Union[str, Sequence[str], None] = "e1fd5f174f86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
