"""add booking status and telegram_user_id fields

Revision ID: 1b0a40cfcc4f
Revises: fbccadc062c0
Create Date: 2026-01-30 16:46:48.475587

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b0a40cfcc4f"
down_revision: Union[str, Sequence[str], None] = "fbccadc062c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    booking_status_enum = sa.Enum(
        "PENDING", "CONFIRMED", "CANCELLED", "EXPIRED", name="bookingstatus"
    )
    booking_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column(
            "status", booking_status_enum, nullable=False, server_default="PENDING"
        ),
    )
    op.add_column("bookings", sa.Column("telegram_user_id", sa.Integer(), nullable=True))
    op.drop_column("bookings", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            server_default="False",
        ),
    )
    op.drop_column("bookings", "telegram_user_id")
    op.drop_column("bookings", "status")
    # ### end Alembic commands ###
