"""fix is_active filed in reviews table

Revision ID: 2d9f7edb9165
Revises: 07a2c3db5711
Create Date: 2025-12-07 01:14:35.807697

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2d9f7edb9165"
down_revision: Union[str, Sequence[str], None] = "07a2c3db5711"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
