"""add booking created and confirm date fields

Revision ID: 55469ef41a42
Revises: d5410078fbee
Create Date: 2026-01-11 12:08:28.714649

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55469ef41a42"
down_revision: Union[str, Sequence[str], None] = "d5410078fbee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings", sa.Column("booking_created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "bookings", sa.Column("booking_confirmed_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###

    op.execute(
        "UPDATE bookings SET booking_created_at = NOW() WHERE booking_created_at IS NULL"
    )

    op.alter_column(
        "bookings", "booking_created_at", existing_type=sa.DateTime(), nullable=False
    )

    op.execute("ALTER TABLE bookings ALTER COLUMN booking_created_at SET DEFAULT NOW()")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "booking_confirmed_at")
    op.drop_column("bookings", "booking_created_at")
    # ### end Alembic commands ###
