"""add is_ctive column to booking table

Revision ID: 6606f49cd852
Revises: 10d56fb11c77
Create Date: 2025-12-07 20:45:28.728348

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6606f49cd852"
down_revision: Union[str, Sequence[str], None] = "10d56fb11c77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "is_active")
    # ### end Alembic commands ###
