"""add excursion images urls table

Revision ID: 8247a84532d5
Revises: a5186dbaf831
Create Date: 2025-12-10 15:12:18.583845

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8247a84532d5"
down_revision: Union[str, Sequence[str], None] = "a5186dbaf831"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "excursion_images",
        sa.Column("excursion_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["excursion_id"], ["excursions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("excursions", "image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "excursions",
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_table("excursion_images")
    # ### end Alembic commands ###
