"""rework is_active field in excursions model

Revision ID: 82873112a413
Revises: 8f3633d98d63
Create Date: 2026-02-04 04:16:55.885076

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "82873112a413"
down_revision: Union[str, Sequence[str], None] = "8f3633d98d63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
