"""add user info fields

Revision ID: 8e25c7bd7519
Revises: ac1bdbb026ce
Create Date: 2026-03-20 01:57:52.137315

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e25c7bd7519"
down_revision: Union[str, Sequence[str], None] = "ac1bdbb026ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "telegram_user_id")
    op.drop_column("bookings", "telegram_message_id")
    op.add_column(
        "users",
        sa.Column("phone_number", sa.String(), nullable=False),
    )
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "email_confirmed_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.add_column("users", sa.Column("phone_confirmed_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_column("users", "phone_confirmed_at")
    op.drop_column("users", "email_confirmed_at")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "phone_number")
    op.add_column(
        "bookings",
        sa.Column(
            "telegram_message_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "bookings",
        sa.Column("telegram_user_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
