"""add on_update value for chaged_at filed

Revision ID: 8f3633d98d63
Revises: 0a66d343d9f5
Create Date: 2026-02-02 04:26:33.610148

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8f3633d98d63"
down_revision: Union[str, Sequence[str], None] = "0a66d343d9f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
