"""fix excursion_id in booking table

Revision ID: a5186dbaf831
Revises: cc596189b64a
Create Date: 2025-12-07 21:17:14.538624

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5186dbaf831"
down_revision: Union[str, Sequence[str], None] = "cc596189b64a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("bookings_excursion_id_key"), "bookings", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("bookings_excursion_id_key"),
        "bookings",
        ["excursion_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
