"""add excursion type

Revision ID: ac1bdbb026ce
Revises: ec7067457785
Create Date: 2026-02-21 16:29:22.245052

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac1bdbb026ce"
down_revision: Union[str, Sequence[str], None] = "ec7067457785"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    excursion_type = sa.Enum("EXCURSION", "TOUR", name="excursiontype")
    excursion_type.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "excursions",
        sa.Column("type", excursion_type, nullable=False, server_default="EXCURSION"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("excursions", "type")
    # ### end Alembic commands ###
