"""add booking city

Revision ID: acbd0dc0fed7
Revises: 04561ada7418
Create Date: 2026-02-17 01:22:12.365052

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "acbd0dc0fed7"
down_revision: Union[str, Sequence[str], None] = "04561ada7418"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("city", sa.String(), nullable=False, server_default="Симферополь"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "city")
    # ### end Alembic commands ###
