"""change name for confirmed_at to changed_at filed

Revision ID: b30e66a75ec2
Revises: 1b0a40cfcc4f
Create Date: 2026-02-02 04:22:29.831212

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b30e66a75ec2"
down_revision: Union[str, Sequence[str], None] = "1b0a40cfcc4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("changed_at", sa.DateTime(), nullable=True))
    op.drop_column("bookings", "confirmed_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column(
            "confirmed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("bookings", "changed_at")
    # ### end Alembic commands ###
