"""change excursions table

Revision ID: b65a22e24f93
Revises: e5af8285e883
Create Date: 2025-12-06 14:29:52.123368

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b65a22e24f93"
down_revision: Union[str, Sequence[str], None] = "e5af8285e883"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_excursion_id"), table_name="reviews")
    op.drop_table("reviews")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("excursion_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "author_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("rating", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_approved", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["excursion_id"], ["excursions.id"], name=op.f("reviews_excursion_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("reviews_pkey")),
    )
    op.create_index(
        op.f("ix_reviews_excursion_id"), "reviews", ["excursion_id"], unique=False
    )
    # ### end Alembic commands ###
