"""remove category field

Revision ID: bb1f49877f5b
Revises: 8247a84532d5
Create Date: 2025-12-21 01:26:30.226330

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bb1f49877f5b"
down_revision: Union[str, Sequence[str], None] = "8247a84532d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "excursions",
        "date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.drop_column("excursions", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "excursions",
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "excursions",
        "date",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
