"""change excursion_id in bookings from str to int

Revision ID: cc596189b64a
Revises: 6606f49cd852
Create Date: 2025-12-07 20:53:00.507243

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc596189b64a"
down_revision: Union[str, Sequence[str], None] = "6606f49cd852"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("excursion_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("total_people", sa.Integer(), nullable=False),
        sa.Column("children", sa.Integer(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("bookings", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, "bookings", ["excursion_id"])
    op.create_foreign_key(
        None, "bookings", "excursions", ["excursion_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bookings", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "bookings", type_="unique")  # type: ignore
    op.alter_column(
        "bookings",
        "excursion_id",
        existing_type=sa.BigInteger(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
