"""remove duration field

Revision ID: e1c5623a012f
Revises: bb1f49877f5b
Create Date: 2025-12-21 02:55:36.723915

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1c5623a012f"
down_revision: Union[str, Sequence[str], None] = "bb1f49877f5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("excursions", "duration")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "excursions",
        sa.Column("duration", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
