"""add excursion cities

Revision ID: ec7067457785
Revises: acbd0dc0fed7
Create Date: 2026-02-17 01:34:10.397445

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec7067457785"
down_revision: Union[str, Sequence[str], None] = "acbd0dc0fed7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "excursions",
        sa.Column("cities", sa.JSON(), nullable=False, server_default="{}"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("excursions", "cities")
    # ### end Alembic commands ###
