"""change name of created_at and confirmed_at fileds

Revision ID: fbccadc062c0
Revises: 55469ef41a42
Create Date: 2026-01-11 12:19:03.260779

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fbccadc062c0"
down_revision: Union[str, Sequence[str], None] = "55469ef41a42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("bookings", sa.Column("confirmed_at", sa.DateTime(), nullable=True))
    op.drop_column("bookings", "booking_confirmed_at")
    op.drop_column("bookings", "booking_created_at")
    # ### end Alembic commands ###

    op.execute("UPDATE bookings SET created_at = NOW() WHERE created_at IS NULL")

    op.alter_column(
        "bookings", "created_at", existing_type=sa.DateTime(), nullable=False
    )

    op.execute("ALTER TABLE bookings ALTER COLUMN created_at SET DEFAULT NOW()")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column(
            "booking_created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "booking_confirmed_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("bookings", "confirmed_at")
    op.drop_column("bookings", "created_at")
    # ### end Alembic commands ###
